'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Arrays.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insufficient space!.
        '''</summary>
        Friend ReadOnly Property ArrayOverflowError() As String
            Get
                Return ResourceManager.GetString("ArrayOverflowError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No elements to delete!.
        '''</summary>
        Friend ReadOnly Property ArrayUnderflowError() As String
            Get
                Return ResourceManager.GetString("ArrayUnderflowError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to What do you want to edit?.
        '''</summary>
        Friend ReadOnly Property ChooseDataToEditPrompt() As String
            Get
                Return ResourceManager.GetString("ChooseDataToEditPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to What do you want to delete?.
        '''</summary>
        Friend ReadOnly Property ChooseDateToDeletePrompt() As String
            Get
                Return ResourceManager.GetString("ChooseDateToDeletePrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit now:.
        '''</summary>
        Friend ReadOnly Property ChooseNewValuePrompt() As String
            Get
                Return ResourceManager.GetString("ChooseNewValuePrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data does not exist!.
        '''</summary>
        Friend ReadOnly Property DataNonExistentError() As String
            Get
                Return ResourceManager.GetString("DataNonExistentError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter new data:.
        '''</summary>
        Friend ReadOnly Property EnterNewDataPrompt() As String
            Get
                Return ResourceManager.GetString("EnterNewDataPrompt", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Where do you want to add it?.
        '''</summary>
        Friend ReadOnly Property InsertLocationPrompt() As String
            Get
                Return ResourceManager.GetString("InsertLocationPrompt", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The position must be between 0 and {0}.
        '''</summary>
        Friend ReadOnly Property InvalidIndexError() As String
            Get
                Return ResourceManager.GetString("InvalidIndexError", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The position must be a valid number!.
        '''</summary>
        Friend ReadOnly Property InvalidNumberError() As String
            Get
                Return ResourceManager.GetString("InvalidNumberError", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
